server:
  port: 8082

info:
  app:
    description: "Order Worker Service - Processamento e PersistÃªncia (Ambev Integration)"

spring:
  application:
    name: order-service

  main:
    banner-mode: "console"
    allow-bean-definition-overriding: true

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongo:27017/orders_db}
      auto-index-creation: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 2000ms
          max-attempts: 5

iam:
  jwt-secret: ${JWT_SECRET:M2I3YzA5OGU1YmFhN2U3Zjk0ZWY0ZGIyYmU5ZDBjZjkxZWRhYmFmNjA4MGY1ZDIzM2M4ZGM0ZTI5N2I0YmU3YQ==}

logging:
  level:
    root: INFO
    com.br.order_service: DEBUG
    org.springframework.data.mongodb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
  endpoint:
    health:
      show-details: always